#!/bin/bash

if [[ $1 =~ ^[0-9]*$ ]]; then
    CONTAINER=$1
    shift
    COMMAND=$@
    echo -ne "\e[1;32mexecuting \"$COMMAND\" in container #${CONTAINER} ($(grep -m 1 hostname /etc>
    pct exec $CONTAINER -- /bin/bash -c "$COMMAND"
fi
