#!/bin/bash

CONTAINERS=( $(pct list | grep running | awk '{print $1}') )

apt_update() {
./lxc-exec $CONTAINER "apt-get update"
./lxc-exec $CONTAINER "apt-get dist-upgrade -y"
./lxc-exec $CONTAINER "apt-get clean"
./lxc-exec $CONTAINER "apt-get autoremove -y"
}

for CONTAINER in ${CONTAINERS[@]}
do
  apt_update
done
